package com.smileidentity.models.v2.metadata

enum class MetadataKey(val key: String) {
    ActiveLivenessType("active_liveness_type"),
    ActiveLivenessVersion("active_liveness_version"),
    CameraName("camera_name"),
    CarrierInfo("carrier_info"),
    ClientIP("client_ip"),
    DeviceModel("device_model"),
    DeviceOrientation("device_orientation"),
    DeviceOS("device_os"),
    DocumentBackCaptureRetries("document_back_capture_retries"),
    DocumentBackCaptureDuration("document_back_capture_duration_ms"),
    DocumentBackImageOrigin("document_back_image_origin"),
    DocumentFrontCaptureRetries("document_front_capture_retries"),
    DocumentFrontCaptureDuration("document_front_capture_duration_ms"),
    DocumentFrontImageOrigin("document_front_image_origin"),
    Fingerprint("fingerprint"),
    HostApplication("host_application"),
    Locale("locale"),
    LocalTimeOfEnrolment("local_time_of_enrolment"),
    MemoryInfo("memory_info"),
    NetworkConnection("network_connection"),
    NumberOfCameras("number_of_cameras"),
    ProxyDetected("proxy"),
    ScreenResolution("screen_resolution"),
    SelfieCaptureDuration("selfie_capture_duration_ms"),
    SelfieImageOrigin("selfie_image_origin"),
    Sdk("sdk"),
    SdkVersion("sdk_version"),
    SystemArchitecture("system_architecture"),
    Timezone("timezone"),
    VPNDetected("vpn"),
}
