---
title: Navigation/root Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
navigation/root(["RootGraph"]) -- "start" --- navigation/orchestrated_instructions_screen("OrchestratedInstructionsScreen")
navigation/root(["RootGraph"]) --- navigation/orchestrated_capture_screen("OrchestratedCaptureScreen")
navigation/root(["RootGraph"]) --- navigation/orchestrated_preview_screen("OrchestratedPreviewScreen")
navigation/root(["RootGraph"]) --- navigation/orchestrated_processing_screen("OrchestratedProcessingScreen")


classDef destination fill:#5383EC,stroke:#ffffff;
class navigation/orchestrated_capture_screen,navigation/orchestrated_instructions_screen,navigation/orchestrated_preview_screen,navigation/orchestrated_processing_screen destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class navigation/root navgraph;
