# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "America/Los_Angeles"
    groups:
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      # Group updates together, so that they are all applied in a single PR.
      kotlin:
        # KSP and Kotlin updates need to be applied simultaneously
        patterns:
          - "com.google.devtools.ksp"
          - "org.jetbrains.kotlin.*"
          - "dev.zacsweers.moshix"
      all:
        # Group all patch and minor updates together. Kotlin/KSP updates belong to the first group
        # so they will not be updated as part of this group
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Los_Angeles"
    groups:
      github-actions:
        patterns:
          - "*"
