name: 'Close stale PRs'
on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'This PR is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-stale: 14
          days-before-close: 7
          days-before-issue-stale: -1
          days-before-issue-close: -1
